# Generated by Django 5.0.7 on 2024-07-18 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_company_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
