# Generated by Django 5.0.8 on 2024-11-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_next_sale_days'),
        ('product', '0047_warehouseozon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together={('product', 'company', 'warehouse', 'marketplace_type')},
        ),
    ]
