# Generated by Django 5.0.8 on 2024-11-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_alter_productorder_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productorder',
            unique_together=set(),
        ),
    ]
