# Generated by Django 5.0.7 on 2024-07-18 09:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceservice', '0002_rename_id_ozon_uuid_rename_id_wildberries_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wildberries',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
