# Generated by Django 5.0.7 on 2024-07-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceservice', '0003_alter_wildberries_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozon',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='wildberries',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='yandexmarket',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
