# Generated by Django 5.0.7 on 2024-07-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceservice', '0004_alter_ozon_updated_at_alter_wildberries_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wildberries',
            managers=[
            ],
        ),
    ]
